name: Build Debug APK Only

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android debug APK
        run: flutter build apk --debug

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/*.apk
      - name: Create Release and upload APK
        uses: ncipollo/release-action@v1
        with:
          tag: debug-apk-${{ github.run_id }}
          name: Debug APK ${{ github.run_number }}
          files: build/app/outputs/flutter-apk/*.apk
